import { Type } from '@angular/core';

export type ToolUiLoader = () => Promise<Type<unknown>>;

/** Lazy loaders for all interactive tool UIs (keeps tool route shell small). */
export const TOOL_UI_LOADERS: Record<string, ToolUiLoader> = {
  'age-calculator': () => import('./tool-uis/age-calculator.component').then(m => m.AgeCalculatorComponent),
  'area-converter': () => import('./tool-uis/area-converter.component').then(m => m.AreaConverterComponent),
  'aspect-ratio-calculator': () => import('./tool-uis/aspect-ratio-calculator.component').then(m => m.AspectRatioCalculatorComponent),
  'backlink-checker': () => import('./tool-uis/url-encoder-backlink.component').then(m => m.BacklinkCheckerComponent),
  'barcode-generator': () => import('./tool-uis/utility-tools-1.component').then(m => m.BarcodeGeneratorComponent),
  'base-converter': () => import('./tool-uis/utility-tools-2.component').then(m => m.BaseConverterComponent),
  'base64-encoder': () => import('./tool-uis/base64-encoder.component').then(m => m.Base64EncoderComponent),
  'bcrypt-generator': () => import('./tool-uis/cors-csp-bcrypt.component').then(m => m.BcryptGeneratorComponent),
  'bitrate-calculator': () => import('./tool-uis/bitrate-calculator.component').then(m => m.BitrateCalculatorComponent),
  'bmi-calculator': () => import('./tool-uis/bmi-calculator.component').then(m => m.BmiCalculatorComponent),
  'cagr-calculator': () => import('./tool-uis/calculator-all.component').then(m => m.CagrCalculatorComponent),
  'calorie-calculator': () => import('./tool-uis/calorie-calculator.component').then(m => m.CalorieCalculatorComponent),
  'codec-comparison': () => import('./tool-uis/codec-comparison.component').then(m => m.CodecComparisonComponent),
  'color-converter': () => import('./tool-uis/cron-color-diff.component').then(m => m.ColorConverterComponent),
  'color-picker': () => import('./tool-uis/utility-tools-1.component').then(m => m.ColorPickerToolComponent),
  'color-space-converter': () => import('./tool-uis/color-space-converter.component').then(m => m.ColorSpaceConverterComponent),
  'compound-interest-calculator': () => import('./tool-uis/compound-interest-calculator.component').then(m => m.CompoundInterestCalculatorComponent),
  'compression-calculator': () => import('./tool-uis/compression-calculator.component').then(m => m.CompressionCalculatorComponent),
  'cors-tester': () => import('./tool-uis/cors-csp-bcrypt.component').then(m => m.CorsTesterComponent),
  'cron-generator': () => import('./tool-uis/cron-color-diff.component').then(m => m.CronGeneratorComponent),
  'crop-yield-calculator': () => import('./tool-uis/crop-yield-calculator.component').then(m => m.CropYieldCalculatorComponent),
  'csp-generator': () => import('./tool-uis/cors-csp-bcrypt.component').then(m => m.CspGeneratorComponent),
  'currency-converter': () => import('./tool-uis/calculator-all.component').then(m => m.CurrencyConverterComponent),
  'data-converter': () => import('./tool-uis/data-converter.component').then(m => m.DataConverterComponent),
  'diff-checker': () => import('./tool-uis/cron-color-diff.component').then(m => m.DiffCheckerComponent),
  'discount-calculator': () => import('./tool-uis/discount-calculator.component').then(m => m.DiscountCalculatorComponent),
  'duplicate-line-remover': () => import('./tool-uis/lorem-duplicate-findreplace.component').then(m => m.DuplicateLineRemoverComponent),
  'duration-calculator': () => import('./tool-uis/duration-calculator.component').then(m => m.DurationCalculatorComponent),
  'emi-calculator': () => import('./tool-uis/emi-calculator.component').then(m => m.EmiCalculatorComponent),
  'energy-converter': () => import('./tool-uis/energy-converter.component').then(m => m.EnergyConverterComponent),
  'farm-income-calculator': () => import('./tool-uis/seed-pesticide-income-livestock.component').then(m => m.FarmIncomeCalculatorComponent),
  'fd-calculator': () => import('./tool-uis/calculator-all.component').then(m => m.FdCalculatorComponent),
  'fertilizer-calculator': () => import('./tool-uis/fertilizer-calculator.component').then(m => m.FertilizerCalculatorComponent),
  'find-and-replace': () => import('./tool-uis/lorem-duplicate-findreplace.component').then(m => m.FindReplaceComponent),
  'frame-rate-converter': () => import('./tool-uis/frame-rate-converter.component').then(m => m.FrameRateConverterComponent),
  'fuel-converter': () => import('./tool-uis/fuel-converter.component').then(m => m.FuelConverterComponent),
  'fuel-cost-calculator': () => import('./tool-uis/calculator-all.component').then(m => m.FuelCostCalculatorComponent),
  'gif-maker': () => import('./tool-uis/video-trimmer-gif.component').then(m => m.GifMakerComponent),
  'gst-calculator': () => import('./tool-uis/gst-calculator.component').then(m => m.GstCalculatorComponent),
  'hash-generator': () => import('./tool-uis/hash-generator.component').then(m => m.HashGeneratorComponent),
  'hmac-generator': () => import('./tool-uis/hmac-ssl-ip.component').then(m => m.HmacGeneratorComponent),
  'image-color-picker': () => import('./tool-uis/image-misc-components').then(m => m.ImageColorPickerComponent),
  'image-compressor': () => import('./tool-uis/image-compressor.component').then(m => m.ImageCompressorComponent),
  'image-converter': () => import('./tool-uis/image-converter.component').then(m => m.ImageConverterComponent),
  'image-cropper': () => import('./tool-uis/image-cropper.component').then(m => m.ImageCropperComponent),
  'image-flip-rotate': () => import('./tool-uis/image-flip-rotate.component').then(m => m.ImageFlipRotateComponent),
  'image-resizer': () => import('./tool-uis/image-resizer.component').then(m => m.ImageResizerComponent),
  'image-to-base64': () => import('./tool-uis/image-misc-components').then(m => m.ImageToBase64Component),
  'image-watermark': () => import('./tool-uis/image-watermark.component').then(m => m.ImageWatermarkComponent),
  'ip-lookup': () => import('./tool-uis/utility-tools-1.component').then(m => m.IpLookupComponent),
  'irrigation-calculator': () => import('./tool-uis/irrigation-soilph.component').then(m => m.IrrigationCalculatorComponent),
  'jpg-to-png': () => import('./tool-uis/image-misc-components').then(m => m.JpgToPngComponent),
  'json-formatter': () => import('./tool-uis/json-formatter.component').then(m => m.JsonFormatterComponent),
  'jsonld-generator': () => import('./tool-uis/seo-tools-all.component').then(m => m.JsonLdGeneratorComponent),
  'jwt-decoder': () => import('./tool-uis/markdown-jwt.component').then(m => m.JwtDecoderComponent),
  'keyword-density-checker': () => import('./tool-uis/keyword-density-checker.component').then(m => m.KeywordDensityCheckerComponent),
  'length-converter': () => import('./tool-uis/length-converter.component').then(m => m.LengthConverterComponent),
  'line-sorter': () => import('./tool-uis/slug-reverser-sorter-encoder-diff.component').then(m => m.LineSorterComponent),
  'livestock-feed-calculator': () => import('./tool-uis/seed-pesticide-income-livestock.component').then(m => m.LivestockFeedCalculatorComponent),
  'loan-comparison': () => import('./tool-uis/calculator-all.component').then(m => m.LoanComparisonComponent),
  'lorem-ipsum-generator': () => import('./tool-uis/lorem-duplicate-findreplace.component').then(m => m.LoremIpsumGeneratorComponent),
  'markdown-editor': () => import('./tool-uis/markdown-jwt.component').then(m => m.MarkdownEditorComponent),
  'meta-tag-generator': () => import('./tool-uis/meta-tag-generator.component').then(m => m.MetaTagGeneratorComponent),
  'morse-code-converter': () => import('./tool-uis/utility-tools-2.component').then(m => m.MorseCodeConverterComponent),
  'msp-calculator': () => import('./tool-uis/weather-msp.component').then(m => m.MspCalculatorComponent),
  'og-generator': () => import('./tool-uis/seo-tools-all.component').then(m => m.OgGeneratorComponent),
  'open-graph-tester': () => import('./tool-uis/seo-tools-all.component').then(m => m.OpenGraphTesterComponent),
  'page-speed-analyzer': () => import('./tool-uis/seo-tools-all.component').then(m => m.PageSpeedAnalyzerComponent),
  'password-generator': () => import('./tool-uis/password-generator.component').then(m => m.PasswordGeneratorComponent),
  'password-strength-checker': () => import('./tool-uis/hash-password-strength.component').then(m => m.PasswordStrengthCheckerComponent),
  'percentage-calculator': () => import('./tool-uis/percentage-calculator.component').then(m => m.PercentageCalculatorComponent),
  'pesticide-calculator': () => import('./tool-uis/seed-pesticide-income-livestock.component').then(m => m.PesticideCalculatorComponent),
  'png-to-jpg': () => import('./tool-uis/image-misc-components').then(m => m.PngToJpgComponent),
  'pomodoro-timer': () => import('./tool-uis/utility-tools-2.component').then(m => m.PomodoroComponent),
  'ppf-calculator': () => import('./tool-uis/calculator-all.component').then(m => m.PpfCalculatorComponent),
  'pressure-converter': () => import('./tool-uis/pressure-converter.component').then(m => m.PressureConverterComponent),
  'qr-code-generator': () => import('./tool-uis/qr-generator.component').then(m => m.QrGeneratorComponent),
  'rd-calculator': () => import('./tool-uis/calculator-all.component').then(m => m.RdCalculatorComponent),
  'readability-checker': () => import('./tool-uis/seo-tools-all.component').then(m => m.ReadabilityCheckerComponent),
  'regex-tester': () => import('./tool-uis/url-encoder-regex-uuid.component').then(m => m.RegexTesterComponent),
  'resolution-converter': () => import('./tool-uis/resolution-converter.component').then(m => m.ResolutionConverterComponent),
  'retirement-calculator': () => import('./tool-uis/retirement-calculator.component').then(m => m.RetirementCalculatorComponent),
  'robots-txt-generator': () => import('./tool-uis/seo-tools-all.component').then(m => m.RobotsTxtGeneratorComponent),
  'roman-numeral-converter': () => import('./tool-uis/utility-tools-1.component').then(m => m.RomanNumeralConverterComponent),
  'schema-markup-generator': () => import('./tool-uis/seo-tools-all.component').then(m => m.SchemaMarkupGeneratorComponent),
  'screen-recorder': () => import('./tool-uis/video-rotate-recorder-subtitle-merger.component').then(m => m.ScreenRecorderComponent),
  'screen-recording-calculator': () => import('./tool-uis/screen-recording-calculator.component').then(m => m.ScreenRecordingCalculatorComponent),
  'screen-ruler': () => import('./tool-uis/utility-tools-2.component').then(m => m.ScreenRulerComponent),
  'seed-rate-calculator': () => import('./tool-uis/seed-pesticide-income-livestock.component').then(m => m.SeedRateCalculatorComponent),
  'sip-calculator': () => import('./tool-uis/sip-calculator.component').then(m => m.SipCalculatorComponent),
  'sitemap-generator': () => import('./tool-uis/seo-tools-all.component').then(m => m.SitemapGeneratorComponent),
  'soil-ph-calculator': () => import('./tool-uis/irrigation-soilph.component').then(m => m.SoilPhCalculatorComponent),
  'speed-converter': () => import('./tool-uis/speed-converter.component').then(m => m.SpeedConverterComponent),
  'ssl-checker': () => import('./tool-uis/hmac-ssl-ip.component').then(m => m.SslCheckerComponent),
  'stopwatch-timer': () => import('./tool-uis/utility-tools-2.component').then(m => m.StopwatchTimerComponent),
  'string-encoder': () => import('./tool-uis/slug-reverser-sorter-encoder-diff.component').then(m => m.StringEncoderComponent),
  'subtitle-timing-calculator': () => import('./tool-uis/subtitle-timing-calculator.component').then(m => m.SubtitleTimingCalculatorComponent),
  'temperature-converter': () => import('./tool-uis/temperature-converter.component').then(m => m.TemperatureConverterComponent),
  'text-case-converter': () => import('./tool-uis/text-case-converter.component').then(m => m.TextCaseConverterComponent),
  'text-diff-highlighter': () => import('./tool-uis/slug-reverser-sorter-encoder-diff.component').then(m => m.TextDiffHighlighterComponent),
  'text-reverser': () => import('./tool-uis/slug-reverser-sorter-encoder-diff.component').then(m => m.TextReverserComponent),
  'text-to-slug': () => import('./tool-uis/slug-reverser-sorter-encoder-diff.component').then(m => m.TextToSlugComponent),
  'text-to-speech': () => import('./tool-uis/utility-tools-2.component').then(m => m.TextToSpeechComponent),
  'time-converter': () => import('./tool-uis/time-converter.component').then(m => m.TimeConverterComponent),
  'timestamp-converter': () => import('./tool-uis/utility-tools-1.component').then(m => m.TimestampConverterComponent),
  'tip-calculator': () => import('./tool-uis/calculator-all.component').then(m => m.TipCalculatorComponent),
  'title-description-analyzer': () => import('./tool-uis/seo-tools-all.component').then(m => m.TitleDescriptionAnalyzerComponent),
  'twitter-card-generator': () => import('./tool-uis/seo-tools-all.component').then(m => m.TwitterCardGeneratorComponent),
  'url-encoder': () => import('./tool-uis/utility-tools-1.component').then(m => m.UrlEncoderComponent),
  'uuid-generator': () => import('./tool-uis/url-encoder-regex-uuid.component').then(m => m.UuidGeneratorComponent),
  'vat-calculator': () => import('./tool-uis/calculator-all.component').then(m => m.VatCalculatorComponent),
  'video-compressor': () => import('./tool-uis/video-compressor-converter.component').then(m => m.VideoCompressorComponent),
  'video-converter': () => import('./tool-uis/video-compressor-converter.component').then(m => m.VideoConverterComponent),
  'video-merger': () => import('./tool-uis/video-rotate-recorder-subtitle-merger.component').then(m => m.VideoMergerComponent),
  'video-rotate': () => import('./tool-uis/video-rotate-recorder-subtitle-merger.component').then(m => m.VideoRotateComponent),
  'video-speed-changer': () => import('./tool-uis/video-mp3-speed.component').then(m => m.VideoSpeedChangerComponent),
  'video-subtitle-adder': () => import('./tool-uis/video-rotate-recorder-subtitle-merger.component').then(m => m.VideoSubtitleAdderComponent),
  'video-to-mp3': () => import('./tool-uis/video-mp3-speed.component').then(m => m.VideoToMp3Component),
  'video-trimmer': () => import('./tool-uis/video-trimmer-gif.component').then(m => m.VideoTrimmerComponent),
  'volume-converter': () => import('./tool-uis/volume-converter.component').then(m => m.VolumeConverterComponent),
  'weather-crop-advisor': () => import('./tool-uis/weather-msp.component').then(m => m.WeatherCropAdvisorComponent),
  'word-counter': () => import('./tool-uis/word-counter.component').then(m => m.WordCounterComponent),
};

/** Heavy UIs intentionally deferred to separate chunks. */
export const TOOL_UI_DEFERRED_SLUGS = [
  'backlink-checker',
  'gif-maker',
  'image-color-picker',
  'image-compressor',
  'image-converter',
  'image-cropper',
  'image-flip-rotate',
  'image-resizer',
  'image-to-base64',
  'image-watermark',
  'jpg-to-png',
  'jsonld-generator',
  'page-speed-analyzer',
  'png-to-jpg',
  'schema-markup-generator',
  'screen-recorder',
  'video-compressor',
  'video-converter',
  'video-merger',
  'video-rotate',
  'video-speed-changer',
  'video-subtitle-adder',
  'video-to-mp3',
  'video-trimmer',
] as const;
